global:
  scrape_interval: 5s
  evaluation_interval: 30s
scrape_configs:
- job_name: eshop-monitoring
  honor_labels: true
  static_configs:
  - targets: ['product-service:3000', 'order-service:3000']