apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /home/rob/apps/kompose convert -f eshop-compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: eshop-ui
  name: eshop-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eshop-ui
  template:
    metadata:
      annotations:
        kompose.cmd: /home/rob/apps/kompose convert -f eshop-compose.yaml
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: eshop-ui
    spec:
      containers:
        - image: eshopContainerRegistryXYZ.azurecr.io/eshop-aks/ui
          name: ui
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: VITE_PRODUCT_SERVICE
              value: "http://4.151.40.45:9090"
            - name: VITE_ORDER_SERVICE
              value: "http://4.151.40.78:9091"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always
