apiVersion: v1
data:
  prometheus.yaml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 30s
    scrape_configs:
    - job_name: eshop-monitoring
      honor_labels: true
      static_configs:
      - targets: ['10.0.223.56:9090', '10.0.168.5:9091']
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: prometheus
  name: prometheus-cm0
