apiVersion: v1
data:
  prometheus.yaml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 30s
    scrape_configs:
    - job_name: eshop-monitoring
      honor_labels: true
      static_configs:
      - targets: ['https://robert-reyes-dev.xyz/product-service', 'https://robert-reyes-dev.xyz/order-service']
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: prometheus
  name: prometheus-cm0
