apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: splunk-db
  name: splunk-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
